#OSS
novel:
  file:
    endpoint: oss-cn-qingdao.aliyuncs.com #不同的服务器，地址不同
    key-id:  #去OSS控制台获取
    key-secret: #去OSS控制台获取
    bucket-name: buketyzl #这个自己创建bucket时的命名，控制台创建也行，代码创建也行
    file-host: pic #文件路径
    web-url: https://buketyzl.oss-cn-qingdao.aliyuncs.com #OSS文件的web访问地址
